title: DeMachinaMundi Redações
author: "Luís Fernando Campos D'Arcadia"
email: luisfcdarcadia@gmail.com
description: "Website pessoal de Luís Fernando Campos D'Arcadia."
baseurl: "/"
url: "https://luisdarcadia.github.io"
github_username: "luisdarcadia"

img_path: "/assets/img/"
js_path: "/assets/js/"
css_path: "/assets/stylesheet/"

# Build settings
markdown: kramdown
disqus:
  shortname: luisfcdarcadia
googleanalytics: UA-111692123-1
plugins:
  - jekyll-feed
  - jekyll-sitemap
