title: DeMachinaMundi Redações
lang: pt-br
blog_title: DeMachinaMundi
author: "Luís Fernando Campos D'Arcadia"
email: demachinamundi@gmail.com
description: "Aulas de Língua Portuguesa e Revisão Textual - Luís Fernando Campos D'Arcadia."
baseurl: ""
url: "https://luisdarcadia.github.io"
permalink: pretty

github_username: "luisdarcadia"
instagram_username: "demachinamundi"
facebook_username: 'luisfernandocamposd'
linkedin_profile: "https://www.linkedin.com/in/lu%C3%ADs-fernando-campos-d-arcadia-2b2b905a/"
google_analytics: "UA-145580422-1"

img_path: "assets/img"
js_path: "assets/js"
css_path: "assets/css"

defaults:
  - scope:
      type: fichamentos
    values:
      layout: fichamento
      comments: true
      title: "Fichamento"
  - scope:
      type: lusiadas
    values:
      layout: canto
      background: lusiadas
      comments: true

clybaslinks:
  - name: "Atividades"
    link: clybas
  - name: "Instruções"
    link: clybas_instrucoes
  - name: "Material"
    link: clybas_material
  - name: "Dicionários"
    link: dicionarios

navlinks:
  - name: Aulas
    link: alunos
  - name: Revisão de Textos
    link: revisoes
  - name: Sobre
    link: about

collections:
  clybas:
    output: true
    permalink: /clybas/:path
  poemas:
    output: true
    permalink: /poemas/:path
  fichamentos:
    output: true
    permalink: /fichamentos/:path
  lusiadas:
    output: true
    permalink: /lusiadas/:path
    sort_by: ordem

# Build settings
markdown: kramdown
disqus:
  shortname: luisfcdarcadia
plugins:
  - jekyll-feed
