title: DeMachinaMundi Redações
lang: pt-br
blog_title: DeMachinaMundi
author: "Luís Fernando Campos D'Arcadia"
email: luisfcdarcadia@gmail.com
description: "Aulas de Língua Portuguesa e Revisão Textual - Luís Fernando Campos D'Arcadia."
baseurl: ""
url: "luisdarcadia.github.io"
permalink: pretty
github_username: "luisdarcadia"
instagram_username: "luisfcdarcadia"
linkedin_profile: "https://www.linkedin.com/in/lu%C3%ADs-fernando-campos-d-arcadia-2b2b905a/"
img_path: "assets/img"
js_path: "assets/js"
css_path: "assets/css"

navlinks:
  - name: Aulas
    link: aulas
  - name: Revisões
    link: revisoes
  - name: Blog
    link: blog

# Build settings
markdown: kramdown
disqus:
  shortname: luisfcdarcadia
plugins:
  - jekyll-feed
